version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend  # Move into the frontend directory
      - npm install
  build:
    commands:
      - cd frontend
      - npm run build
  post_build:
    commands:
      - aws s3 sync frontend/dist/ s3://www.suhaib.fun/ --delete

artifacts:
  files:
    - frontend/dist/**/*
