version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install  # No need to `cd frontend`, CodeBuild is already there
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://www.suhaib.fun/ --delete  # Remove `frontend/`

artifacts:
  files:
    - dist/**/*
