version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - pip install -r requirements.txt -t .
      - zip -r deploy.zip *
  post_build:
    commands:
      - aws lambda update-function-code --function-name CreatePost --zip-file fileb://deploy.zip
      - aws lambda update-function-code --function-name GetPosts --zip-file fileb://deploy.zip
      - aws lambda update-function-code --function-name GetUploadUrl --zip-file fileb://deploy.zip
      - aws lambda update-function-code --function-name moderate_image --zip-file fileb://deploy.zip

artifacts:
  files:
    - deploy.zip
