version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - cd backend  # Ensure we are in the correct directory
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .

  build:
    commands:
      - zip -r deploy.zip *  # Zip inside backend directory

  post_build:
    commands:
      - aws lambda update-function-code --function-name CreatePost --zip-file fileb://backend/deploy.zip
      - aws lambda update-function-code --function-name GetPosts --zip-file fileb://backend/deploy.zip
      - aws lambda update-function-code --function-name GetUploadUrl --zip-file fileb://backend/deploy.zip
      - aws lambda update-function-code --function-name moderate_image --zip-file fileb://backend/deploy.zip

artifacts:
  files:
    - backend/deploy.zip
